name: hello-world
on:
  push:
    paths: ['!README.md', '**.js']
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed, labeled, unlabeled]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - run: echo "Hello, Today is $TODAY!"
