name: hello-world
on:
  push:
    paths: ['!README.md', '**.js']
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed, labeled, unlabeled]
  workflow_dispatch:
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"
      - run: echo ${{ secrets.DOCKER_USERNAME }}
      - run: echo ${{ secrets.DOCKER_PASSWORD }}
  push-docker-image:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
